name: Update Recent Tracks

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual runs

jobs:
  update-tracks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Fetch Script
        run: node fetch_tracks.mjs

      - name: Create GitHub App Private Key File
        run: echo "${{ secrets.GH_APP_PRIVATE_KEY }}" | base64 --decode > private-key.pem

      - name: Authenticate with GitHub App
        run: |
          APP_ID=${{ secrets.GH_APP_ID }}
          INSTALLATION_ID=${{ secrets.GH_APP_INSTALLATION_ID }}
          PRIVATE_KEY_PATH=private-key.pem

          JWT=$(python3 -c "
          import jwt, time;
          print(jwt.encode({'iat': int(time.time()), 'exp': int(time.time()) + 600, 'iss': '${APP_ID}'}, open('${PRIVATE_KEY_PATH}').read(), algorithm='RS256'))")

          TOKEN=$(curl -s -X POST \
            -H \"Authorization: Bearer $JWT\" \
            -H \"Accept: application/vnd.github.v3+json\" \
            https://api.github.com/app/installations/${INSTALLATION_ID}/access_tokens | jq -r .token)

          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:$TOKEN@github.com/${{ github.repository }}.git

      - name: Commit and Push Changes
        run: |
          git add data/tracks.json
          git commit -m "Update track data from Last.fm" || echo "No changes to commit"
          git push
