name: Update Recent Tracks

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual runs

jobs:
  update-tracks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install node-fetch

      - name: Run Fetch Script
        run: node fetch_tracks.mjs

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add data/tracks.json
          git commit -m "Update track data from Last.fm" || echo "No changes to commit"
          git push
